name: keel_sdk
description: Keel BaaS Flutter SDK - client for Keel backend
version: 0.1.0
homepage: https://github.com/Skndan/keel
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket_channel: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
